// Action Init
export const INITIALIZE_APP = 'INITIALIZE_APP'

// INITIALIZE_APP dispatch all the FETCH actions
// Action when INITIALIZE_APP
export const FETCHING_SINGLE_ROOMS = 'FETCHING_SINGLE_ROOMS'
export const FETCHING_GROUP_ROOMS = 'FETCHING_GROUP_ROOMS'

// Action when FETCHING_SINGLE_ROOMS
export const ADD_SINGLE_ROOM = 'ADD_SINGLE_ROOM'
export const ADDED_SINGLE_ROOM = 'ADDED_SINGLE_ROOM'
export const GOT_SINGLE_ROOM = 'GOT_SINGLE_ROOM'
export const FETCH_ALL_SINGLE_ROOMS = 'FETCH_ALL_SINGLE_ROOMS'
export const REMOVE_SINGLE_ROOM = 'REMOVE_SINGLE_ROOM'
export const REMOVED_SINGLE_ROOM = 'REMOVED_SINGLE_ROOM'
export const GOT_REMOVE_SINGLE_ROOM = 'GOT_REMOVE_SINGLE_ROOM'
export const REMOVE_ALL_SINGLE_ROOMS = 'REMOVE_ALL_SINGLE_ROOMS'
export const UPDATE_SINGLE_ROOM = 'UPDATE_SINGLE_ROOM'
export const GOT_UPDATE_SINGLE_ROOM = 'GOT_UPDATE_SINGLE_ROOM'
export const UPDATED_SINGLE_ROOM = 'UPDATED_SINGLE_ROOM'

// Action when FETCHING_GROUP_ROOMS
export const ADD_GROUP_ROOM = 'ADD_GROUP_ROOM'
export const GOT_GROUP_ROOM = 'GOT_GROUP_ROOM'
export const FETCH_ALL_GROUP_ROOMS = 'FETCH_ALL_GROUP_ROOMS'
export const REMOVE_GROUP_ROOM = 'REMOVE_GROUP_ROOM'
export const REMOVE_ALL_GROUP_ROOMS = 'REMOVE_ALL_GROUP_ROOMS'
export const UPDATE_GROUP_ROOM = 'UPDATE_GROUP_ROOM'
export const GOT_REMOVE_GROUP_ROOM = 'GOT_REMOVE_GROUP_ROOM'
export const GOT_UPDATE_GROUP_ROOM = 'GOT_UPDATE_GROUP_ROOM'


// Action User
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGGING_IN = 'USER_LOGGING_IN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const CHECKING_USER = 'CHECKING_USER'
export const CHECKED_USER = 'CHECKED_USER'

// Action Sidebar
export const OPEN_SIDE_BAR = 'OPEN_SIDE_BAR'
export const CLOSE_SIDE_BAR = 'CLOSE_SIDE_BAR'

//Action Path
export const CHANGE_PATH = 'CHANGE_PATH'

// Other constants
export const HEADER_BAR_TITLE = 'SIMDE'
export const TEST1 = 'TEST1'
export const TEST2 = 'TEST2'
